# Settings for connecting to the database
database:
  # Available options: mariadb, mysql, sqlite
  type: "sqlite"
  # Data for connecting to the MariaDB/MySQL server
  sql:
    host: "localhost"
    port: 3306
    dbname: "my_database"
    username: "user"
    password: "password"

# Plugin language selection. Possible values: "EN", "PL"
language: "EN"

# Should private messages also be blocked when MUTE penalty is applied?
mute_pm: false

# If you set mute_pm to TRUE, you can edit which commands for private messages should be blocked here
mute_cmd:
  - 'me'
  - 'say'
  - 'action'
  - 'eaction'
  - 'describe'
  - 'edescribe'
  - 'eme'
  - 'w'
  - 'm'
  - 'pm'
  - 'whisper'
  - 'ewhisper'
  - 'emsg'
  - 'msg'
  - 'etell'
  - 'tell'
  - 'er'
  - 'r'
  - 'reply'
  - 'ereply'
  - 'ac'
  - 'eac'
  - 'amsg'
  - 'eamsg'
  - 'ehelpop'
  - 'p msg'

# Settings for reactions to the number of received warnings
WarnActions:
  3: "kick {player} You have received your 3rd warning!"
  4: "ban {player} 30m You have received your 4th warning!"
  5: "ban {player} 5h You have received your 5th warning!"
  6: "ban {player} 7d You have received your 6th warning!"
  7: "ban {player} 30d You have received your {warn_no}th warning!"
  10: "ban {player} You have received your 10th warning!"

# Update check and auto-update settings
checkForUpdates: true
autoDownloadUpdates: false

# Debug mode set to true provides more detailed logs in the console
debug: false

# Should StatsCollector be enabled? Recommended setting: true
stats:
  enabled: true