# Settings for connecting to the database
database:
  # Available options: mariadb, mysql, sqlite
  type: "sqlite"
  # Data for connecting to the MariaDB/MySQL server
  sql:
    host: "localhost"
    port: 3306
    dbname: "my_database"
    username: "user"
    password: "password"
# Plugin language selection. Possible values: "PL", "EN"
language: "PL"

# Czy prywatne wiadomości też mają być blokowane przy MUTE?
mute_pm: false

# Jeśli zaznaczyłeś mute_pm na TRUE to tu możesz edytować jakie komendy dla prywatnych wiadomości mają być blokowane
mute_cmd:
  - 'me'
  - 'say'
  - 'action'
  - 'eaction'
  - 'describe'
  - 'edescribe'
  - 'eme'
  - 'w'
  - 'm'
  - 'pm'
  - 'whisper'
  - 'ewhisper'
  - 'emsg'
  - 'msg'
  - 'etell'
  - 'tell'
  - 'er'
  - 'r'
  - 'reply'
  - 'ereply'
  - 'ac'
  - 'eac'
  - 'amsg'
  - 'eamsg'
  - 'ehelpop'
  - 'p msg'

# Update check and auto-update settings
checkForUpdates: true
autoDownloadUpdates: false

# Debug mode set to true provides more detailed logs in the console
debug: false

# Should StatsCollector be enabled? Recommended setting: true
stats:
  enabled: true
