# Settings for connecting to the database
database:
  # Available options: mariadb, mysql, sqlite
  type: "sqlite"
  # Data for connecting to the MariaDB/MySQL server
  sql:
    host: "localhost"
    port: 3306
    dbname: "my_database"
    username: "user"
    password: "password"
# Plugin language selection. Possible values: "PL", "EN"
language: "PL"

# Update check and auto-update settings
checkForUpdates: true
autoDownloadUpdates: false

# Debug mode set to true provides more detailed logs in the console
debug: false

# Should StatsCollector be enabled? Recommended setting: true
stats:
  enabled: true
