name: PunisherX
version: '${version}'
main: pl.syntaxdevteam.PunisherX
api-version: '1.20'
folia-support: true
authors: [SyntaxDevTeam]
description: System kar serwera
website: https://github.com/SyntaxDevTeam
